### PR TITLE
Fixed api imports

### PR DESCRIPTION
**Pull request by ilianovoselov-foodpairing**

### CODE REVIEW

**Comment by ilianovoselov-foodpairing** [comment]
Hey, @benesch, I have more changes to follow, but this needs to be the first, because otherwise there would be conflicts

**Comment by benesch** [comment]
I'm hopeful https://github.com/benesch/kubernetes-stubs/commit/81fd51a086d581e6c6ea3fd845c0170eba9a9d80 will solve your issues. If not, give me a bit more context on the error messages you're seeing, and we can sort it out!

**Comment by ilianovoselov-foodpairing** [comment]
@benesch that's another issue, the one I'm solving here is not solved in your code, Api's are defined in files with suffix _api and you're attempting to import without _api suffix now

**Comment by benesch** [comment]
Ah, apologies, I see it now.

**Pull request merged**
